// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/echoerror.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoError_Echo_FullMethodName = "/echoerror.EchoError/Echo"
)

// EchoErrorClient is the client API for EchoError service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoErrorClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoErrorClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoErrorClient(cc grpc.ClientConnInterface) EchoErrorClient {
	return &echoErrorClient{cc}
}

func (c *echoErrorClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, EchoError_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoErrorServer is the server API for EchoError service.
// All implementations must embed UnimplementedEchoErrorServer
// for forward compatibility.
type EchoErrorServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedEchoErrorServer()
}

// UnimplementedEchoErrorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoErrorServer struct{}

func (UnimplementedEchoErrorServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoErrorServer) mustEmbedUnimplementedEchoErrorServer() {}
func (UnimplementedEchoErrorServer) testEmbeddedByValue()                   {}

// UnsafeEchoErrorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoErrorServer will
// result in compilation errors.
type UnsafeEchoErrorServer interface {
	mustEmbedUnimplementedEchoErrorServer()
}

func RegisterEchoErrorServer(s grpc.ServiceRegistrar, srv EchoErrorServer) {
	// If the following call panics, it indicates UnimplementedEchoErrorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoError_ServiceDesc, srv)
}

func _EchoError_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoErrorServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoError_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoErrorServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoError_ServiceDesc is the grpc.ServiceDesc for EchoError service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoError_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echoerror.EchoError",
	HandlerType: (*EchoErrorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoError_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/echoerror.proto",
}
