apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoerror-client
  labels:
    app: echoerror
    component: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoerror
      component: client
  template:
    metadata:
      labels:
        app: echoerror
        component: client
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/client"]
          env:
            - name: ECHOERROR_HOST
              value: echoerror
            - name: ECHOERROR_PORT
              value: {{ .Values.client.port | quote }}
            - name: ECHOERROR_DELAY_MS
              value: {{ .Values.client.delayMs | quote }}
            - name: ECHOERROR_PAD_MESSAGE_KB
              value: {{ .Values.client.padMessageKb | quote }}
